USE world-cup;

CREATE TABLE TEAM(TeamID CHAR(2) NOT NULL, Team VARCHAR(13), Continent VARCHAR(16), League VARCHAR(40), Population INT, PRIMARY KEY(TeamID));

CREATE TABLE STADIUM(SID CHAR(3) NOT NULL, SName VARCHAR(25), SCity VARCHAR(17), SCapacity INT, PRIMARY KEY(SID));

CREATE TABLE PLAYER(Team VARCHAR(13), TeamID CHAR(2) NOT NULL, PlayerID INT NOT NULL, Position CHAR(2), FIFA_Popular_Name VARCHAR(25), Birth_date CHAR(10), Shirt_Name VARCHAR(25), Club VARCHAR(40), Height INT, Weight INT, PRIMARY KEY(PlayerID, TeamID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID));

CREATE TABLE GAME(GameID CHAR(3) NOT NULL, MatchType CHAR, MatchDate CHAR(9), SID CHAR(3), TeamID1 CHAR(2), TeamID2 CHAR(2), Team1_Score INT, Team2_Score INT, PRIMARY KEY(GameID), FOREIGN KEY(TeamID1) REFERENCES TEAM(TeamID), FOREIGN KEY(TeamID2) REFERENCES TEAM(TeamID));

CREATE TABLE STARTING_LINEUPS(GameID CHAR(3) NOT NULL, TeamID CHAR(2), PlayerID INT, PRIMARY KEY(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID));

CREATE TABLE SUBSTITUTIONS(GameID CHAR(3) NOT NULL, TeamID CHAR(2), PlayerNoIn INT, Position CHAR(2), PlayerNoOut INT, Time INT, PRIMARY KEY(GameID), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerNoIn) REFERENCES PLAYER(PlayerID), FOREIGN KEY(PlayerNoOut) REFERENCES PLAYER(PlayerID), FOREIGN KEY(Position) REFERENCES PLAYER(Position));

CREATE TABLE GOALS(GameID CHAR(3) NOT NULL, TeamID CHAR(2), PlayerID INT, Time INT, Penalty CHAR, PRIMARY KEY(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID));

CREATE TABLE OWN_GOALS(GameID CHAR(3) NOT NULL, TeamID CHAR(2), PlayerID INT, Time INT, For_TeamID, PRIMARY KEY(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID), FOREIGN KEY(For_TeamID) REFERENCES TEAM(TeamID));

CREATE TABLE CARDS(GameID CHAR(3) NOT NULL, TeamID CHAR(2), PlayerID INT, Color VARCHAR(6), Time INT, PRIMARY KEY(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID));